server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://postgres:5432/customer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
  rabbitmq:
    addresses: rabbitmq:5672


management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"