version: "3.8"
# POSTGRES (for Database)
services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
  # PGADMIN (UI for Postgres)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - postgres
  # ZIPKIN (Tracing request flow)
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
  # RABBITMQ (Message queue)
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672" # inter service
      - "15672:15672" # for management console

  #  OUR OWN SERVICES
  #  --> EUREKA-SERVER
  eureka-server:
    image: greengorilla7/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - zipkin
  #  --> API GATEWAY
  api-gateway:
    image: greengorilla7/api-getway:latest
    container_name: api-gateway
    ports:
      - "8083:8083"
    depends_on:
      - zipkin
      - eureka-server
  # --> CUSTOMER
  customer-service:
    image: greengorilla7/customer-service-module:latest
    container_name: customer-service
    ports:
      - "8080:8080"
    depends_on:
      - zipkin
      - eureka-server
  # --> FRAUD
  fraud-service:
    image: greengorilla7/fraud-service-module:latest
    container_name: fraud-service
    ports:
      - "8081:8081"
    depends_on:
      - zipkin
      - eureka-server
      - customer-service
  # --> NOTIFICATION
  notification-service:
    image: greengorilla7/notification-service-module:latest
    container_name: notification-service
    ports:
      - "8082:8082"
    depends_on:
      - zipkin
      - customer-service

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: