server:
  port: 8761

# Because this is the server, no need fetch the registry or register
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

spring:
  application:
    name: eureka-server

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0